.TH ADGUARDHOME 1 "December 2025" "0.107.71" "User Commands"
.SH NAME
adguardhome \- Network-wide ads & trackers blocking DNS server
.SH SYNOPSIS
.B adguardhome
[options]
.SH DESCRIPTION
AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover ALL your home devices, and you don't need any client-side software for that.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR \fIFILE\fR
Path to the config file.
.TP
\fB\-w\fR, \fB\-\-work-dir\fR \fIDIR\fR
Path to the working directory.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print this help.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose output.
.SH AUTHOR
AdGuard Software Ltd
