#!/bin/sh
set -e

case "$1" in
    configure)
        if ! getent passwd adguardhome >/dev/null; then
            adduser --system --group --home /var/lib/adguardhome --no-create-home --disabled-password --quiet adguardhome
        fi

        mkdir -p /var/lib/adguardhome
        chown adguardhome:adguardhome /var/lib/adguardhome
        chmod 755 /var/lib/adguardhome

        mkdir -p /etc/adguardhome
        chown adguardhome:adguardhome /etc/adguardhome
        chmod 755 /etc/adguardhome
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
